name: budget_tracker_application_2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.4.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  material_design_icons_flutter: ^6.0.7096
  flutter_svg: ^1.0.3
  google_fonts: ^6.2.1
  icons_launcher: ^3.0.0
  image_picker: ^0.8.4+8
  intl: ^0.19.0
  lottie: ^3.1.2
  uuid: ^4.5.0
  fl_chart: ^0.36.0

icons_launcher:
  image_path: "assets/icons/wallet.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/animations/Animation - 1727884603463.json
    - assets/animations/Animation - 1727884603463.json
    - assets/animations/signup_animation.json
    - assets/images/S__71032837.jpg
    - assets/images/S__102744079.jpg
    - assets/images/S__143081477.jpg
    - assets/icons/advisor.png
    - assets/icons/bank.png
    - assets/icons/bankruptcy.png
    - assets/icons/bill-payment.png
    - assets/icons/clothes.png
    - assets/icons/delivery-box.png
    - assets/icons/dining.png
    - assets/icons/economic-depression.png
    - assets/icons/electricity-bill.png
    - assets/icons/filling.png
    - assets/icons/financial-goals.png
    - assets/icons/financial.png
    - assets/icons/funds.png
    - assets/icons/gas-station.png
    - assets/icons/graduation.png
    - assets/icons/grocery.png
    - assets/icons/health-check.png
    - assets/icons/house.png
    - assets/icons/insurance.png
    - assets/icons/logistic.png
    - assets/icons/milk.png
    - assets/icons/movie.png
    - assets/icons/internet.png
    - assets/icons/shopping-basket.png
    - assets/icons/smartphone.png
    - assets/icons/stock.png
    - assets/icons/money.png
    - assets/icons/uparrow.png
    - assets/icons/downarrow.png
    - assets/icons/rubbish-bin.png
    - assets/icons/personal.png
    - assets/icons/logout.png
    - assets/icons/camra.png
    - assets/icons/user.png
    - assets/icons/email.png
    - assets/icons/calendar.png
    - assets/icons/back_arrow.png
    - assets/icons/lock.png
    - assets/icons/add.png
    - assets/icons/save.png
    - assets/icons/title.png
    - assets/icons/money-bag.png
    - assets/icons/question.png
    - assets/icons/transaction.png
    - assets/icons/checklist.png
    - assets/icons/about.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
