// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOFBfd_eT1auaH1nohhiNwVdpklapFPlA',
    appId: '1:988715507240:web:fe4a89f266a4ef1c6c5f1d',
    messagingSenderId: '988715507240',
    projectId: 'psnproject-sau',
    authDomain: 'psnproject-sau.firebaseapp.com',
    storageBucket: 'psnproject-sau.appspot.com',
    measurementId: 'G-VCHLX03F7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJLlXhK13wrCipg3J1OhoUn5DpZTXneU0',
    appId: '1:988715507240:android:073b02bb31eb85d46c5f1d',
    messagingSenderId: '988715507240',
    projectId: 'psnproject-sau',
    storageBucket: 'psnproject-sau.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6GVX0OriWzw3inAAkzL2AUROnIXhHMdY',
    appId: '1:988715507240:ios:35c848b36da3019a6c5f1d',
    messagingSenderId: '988715507240',
    projectId: 'psnproject-sau',
    storageBucket: 'psnproject-sau.appspot.com',
    iosBundleId: 'com.example.budgetTrackerApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6GVX0OriWzw3inAAkzL2AUROnIXhHMdY',
    appId: '1:988715507240:ios:35c848b36da3019a6c5f1d',
    messagingSenderId: '988715507240',
    projectId: 'psnproject-sau',
    storageBucket: 'psnproject-sau.appspot.com',
    iosBundleId: 'com.example.budgetTrackerApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOFBfd_eT1auaH1nohhiNwVdpklapFPlA',
    appId: '1:988715507240:web:89a650f94debe4066c5f1d',
    messagingSenderId: '988715507240',
    projectId: 'psnproject-sau',
    authDomain: 'psnproject-sau.firebaseapp.com',
    storageBucket: 'psnproject-sau.appspot.com',
    measurementId: 'G-1XGTX4JV31',
  );
}
